#  menu items

[[main]]
  name = "Workflow"
  weight = 1
  url = "workflows/"

[[main]]
  name = "Docs"
  weight = 2
  url = "docs/"

[[main]]
  name = "Blog"
  weight = 5
  url = "blog/"

# [[main]]
#   name = "Blog"
#   weight = 4
#   url = "blog/"

